stud_corner/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from datetime import datetime
from .models import User
from . import db
from .tokens import generate_confirmation_token, confirm_token, generate_renew_password_token, confirm_renew_password_token
from .email import send_email

auth = Blueprint('auth', __name__)



#Login Page
@auth.route("/signin", methods = ['GET', 'POST'])
def signin():
    if current_user.is_authenticated:
        flash("Sorry, you are already signed in.", "info")
        return redirect(url_for("views.index"))

    if request.method == 'POST':
        #Get the email and password
        email = request.form.get("email")
        password = request.form.get("password")
        if request.form.get("remember"):
            remember = True  
        else:
            remember = False

        user = User.query.filter_by(email=email).first()

        # check if the user actually exists
        # take the user-supplied password, hash it, and compare it to the hashed password in the database
        if not user:
            flash("You entered an invalid email.", "info")
            return redirect(url_for("auth.signin"))
        if not check_password_hash(user.password, password):
            flash("You entered an invalid password.", "info")
            flash("Forgot your password? ", "password-alert")
            return redirect(url_for("auth.signin"))

        if not user.confirmed:
            flash(
                "Your email had not been confirmed. Please check your inbox to confirm your email address and sign in again. Didn't get the email?",
                "unconfirmed_email"
                )
            logout_user()
            return redirect(url_for("auth.signin"))

        login_user(user, remember= remember)
        return redirect(url_for("views.index"))
        
    #Return login page if request is get
    return render_template("/signin.html")

@auth.route("/signout")
@login_required
def signout():
    #Remove user from session and logout
    logout_user()
    return redirect(url_for('auth.signin'))


@auth.route("/signup", methods = ['POST', 'GET'])
def signup():
    if current_user.is_authenticated:
        flash("Sorry, you are already login.", "info")
        return redirect(url_for("views.index"))
    if request.method == "POST":
        #Get the data entered by the user
        firstname = request.form.get("firstname")
        lastname = request.form.get("lastname")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        email = request.form.get("email")
        #Confirm if password matches
        if password1 != password2:
            flash("The passwords you entered do not match.", "info")
            return redirect(url_for("auth.signup"))
        #Min. Length of Password
        if len(password1) < 4:
            flash("Password should be atleast 4 characters.", "info")
            return redirect(url_for("auth.signup"))
        # Check if an account has already been created with the same email address
        user = User.query.filter_by(email=email).first()
        if user:
            flash("An account has already been created with this email address.", "info")
            return redirect(url_for("auth.signup"))

        new_user = User(
            firstname= firstname,
            lastname=lastname,
            email=email, password = generate_password_hash(password1)
            )
        
        db.session.add(new_user)
        db.session.commit()

        token = generate_confirmation_token(new_user.email)
        confirm_url = url_for("auth.confirm_email", token = token, _external = True)
        subject = "Email Confirmation"
        html = render_template("confirm.html", confirm_url = confirm_url)

        send_email(new_user.email, subject, html)

        flash(
            "An email has been sent to you email address. Please click it to activate your account.",
            "success"
            )
        return redirect(url_for('auth.signin'))
    
    return render_template("/signup.html")



#     return email
#### Add a new route to handle the email confirmation
@auth.route("/confirm/<token>")
def confirm_email(token):
    try:
        email = confirm_token(token)

        user = User.query.filter_by(email = email).first_or_404()
        if user.confirmed and current_user.is_authenticated:
            flash("Your account had already been confirmed.", "success")
            return redirect(url_for("views.index"))
        elif user.confirmed and not current_user.is_authenticated:
            flash("Your account had already been confirmed. Please sign in.", "success")
        
        else:
            user.confirmed = True
            user.confirmed_on = datetime.now()
            db.session.add(user)
            db.session.commit()
            flash(
                "Your account is successfully confirmed. Please enter your Email and Password to sign in.",
                "success"
                )

            return redirect(url_for("auth.signin"))
    except:
        return redirect(url_for("auth.error"))

@auth.route('/resend_confirmation', methods = ['POST', 'GET'])
def resend_confirmation():
    if request.method == "POST":
        email = request.form.get("email")
        user = User.query.filter_by(email=email).first()
        if user:
            # Check if the user is already confirmed
            if user.confirmed:
                flash('Your Email address is already confirmed. Please sign in.', 'info')
                return redirect(url_for('auth.signin'))
            token = generate_confirmation_token(email)
            confirm_url = url_for('auth.confirm_email', token=token, _external=True)
            html = render_template('confirm.html', confirm_url=confirm_url)
            subject = "Email Confirmation"
            send_email(user.email, subject, html)
            flash('A new confirmation email has been sent.', 'success')
            return redirect(url_for('auth.signin'))
        else:
            flash("You entered an invalid email.", "info")
            return redirect(url_for("auth.resend_confirmation"))
    return render_template("enter_email.html", title = "Resend Email Confirmation Link")




@auth.route("/reset_password_request", methods = ['POST', 'GET'])
def reset_password_request():
    if request.method == 'POST':
        #Get the user email
        email = request.form.get("email")
        user = User.query.filter_by(email=email).first()
        if user:
            token = generate_renew_password_token(email)
            reset_password_url = url_for('auth.reset_password_form', token=token, _external=True)
            html = render_template('renew_password.html', reset_password_url=reset_password_url)
            subject = "Password Renewal Link"
            send_email(user.email, subject, html)
            flash("An email with a link to renew your password has been sent to your email address.", "success")
        else:
            flash("You entered an invalid email.", "info")

    return render_template("enter_email.html", title = "Reset Password Request")


@auth.route("/reset_password_form/<token>", methods = ['POST', 'GET'])
def reset_password_form(token):
    if request.method == 'POST':
        try:
            email = confirm_renew_password_token(token)

            password1 = request.form.get("password1")
            password2 = request.form.get("password2")
            if password1 != password2:
                flash("The passwords you entered do not match.", "info")
                return redirect(url_for("auth.reset_password_form", token=token))
            #Min. Length of Password
            if len(password1) < 4:
                flash("Password should be atleast 4 characters.", "info")
                return redirect(url_for("auth.reset_password_form", token=token))
            
            user = User.query.filter_by(email = email).first_or_404()
            user.password = generate_password_hash(password1)
            db.session.commit()
            flash(
                "Your password is successfully renewed. Please enter your email and new Password to sign in.",
                "success"
                )
        except:
            flash(
                "The password renewal link is invalid or has expired. Enter your email address again to receive a new link.",
                "danger"
                )
            return redirect(url_for("auth.reset_password_request"))
        return redirect(url_for("auth.signin"))

    return render_template("reset_password_form.html")

    
@auth.route('/error')
def error():
    return render_template("error.html")

stud_corner/templates/app_macros.html
<!--Pagination macros-->
{% macro render_pagination(pagination, endpoint, id="", name="Post page navigation") -%}

  <nav aria-label="{{ name }}">
    <ul class="pagination justify-content-center mt-5">
      <li class="page-item {% if not pagination.has_prev %} disabled {% endif %} ">
          <a class="page-link" href="{{ url_for(endpoint, id=id, page=pagination.prev_num) }}">Previous</a>
      </li>
      {%- for page in pagination.iter_pages(left_edge=1, left_current=1, right_current=2, right_edge=1) %}
          {% if page %}
                {% if page != pagination.page %}
                      <li class="page-item"><a class="page-link" href="{{ url_for(endpoint, id=id, page=page) }}"> {{ page }} </a></li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link"> {{ page }} </span>
                    </li>
                {% endif %}
          {% else %}
              <span>…</span>
          {% endif %}
      {%- endfor %}
              <li class="page-item {% if not pagination.has_next %} disabled {% endif %} ">
                  <a class="page-link" href="{{ url_for(endpoint, id=id, page=pagination.next_num) }}">Next</a>
              </li>
          </ul>      
  </nav>

{%- endmacro %}


<!--Input macros-->
{% macro input(name, type="text", label = "", value = "") -%}
    <input type="{{ type }}" name="{{ name }}" value="{{ value }}" class="form-control" placeholder="name@example.com" autocomplete="off" autofocus required>
    <label for="floatingInput">{{ label }}</label>

{%- endmacro %}

<!--Buttons macros-->
{% macro button(class="w-30 btn btn-lg btn-primary", label = "Submit") -%}
    <button class="{{ class }}" type="submit">{{ label }}</button>
{%- endmacro %}


<!--Textarea macros-->
{% macro textarea(name, id="", value="", label = "") -%}
    <textarea name="{{ name }}" id="{{ id }}" class="form-control" placeholder="This is my post..." required>{{ value }}</textarea>
    <label for="floatingTextarea2">{{ label }}</label>
{%- endmacro %}

stud_corner/templates/confirm.html
<p>Welcome! Thanks for creating an account. Please follow this link to activate your account:</p>
<p class="my-2"><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<p>Thanks for joining us!!!</p>

stud_corner/templates/enter_email.html
{% from "app_macros.html" import input, button with context %}

{% extends "layout.html" %}

{% block title %} {{title}} {% endblock %}

{% block content %}
<div class="container col-11 col-md-4 mt-4">
    <form method="POST">
        <h1 class="h3 fw-normal border-bottom border-secondary">Enter Your Registered Email</h1>
        <div class="form-floating my-3">
            {{ input("email", type="email", label = "Email Address") }}
        </div>
        <div class="d-flex justify-content-center">   
            {{ button() }}
        </div>
    </form> 
</div>
{% endblock %}

stud_corner/templates/error.html
<p>The email confirmation link is invalid or has expired.</p>

stud_corner/templates/index.html
{% from "app_macros.html" import render_pagination with context %}
{% extends "layout.html" %}

{% set active_page = "index" %}

{% block title %}
{% if current_user.is_authenticated %}
    {{ "Welcome %s %s!"%(current_user.firstname, current_user.lastname) }}
{% else %}
    Student Corner
{% endif %}
{% endblock title %}

{% block content %}
<div class="mt-4">
    {% for post in pag_posts.items %}
        <div class="container col-md-7 mt-2 bg">
            <div class="row justify-content-center">
            <div class="row g-0 card-bg border rounded overflow-hidden mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success">{{ post.subject |title }}</strong>
                    <h3 class="mb-0">
                        <a href="{{ url_for('views.read_more', id = post.id) }}" class="text-decoration-none link-dark">
                            {{ post.title |title }}
                        </a>
                    </h3>
                    <div class="mb-1 text-muted">{{ post.date_posted.strftime("%d %B %Y") }} by 
                        <a href="{{ url_for('views.author', id = post.author.id) }}" 
                        class="text-decoration-none link-dark">
                        {{ ("%s %s" %(post.author.firstname, post.author.lastname))|title }}
                        </a>
                    </div>
                    {% if post.content |wordcount > 50 %}
                        <p class="card-text mb-auto content">{{ post.content |urlize|truncate(400) }}</p>
                        <a href="{{ url_for('views.read_more', id = post.id) }}" class="text-decoration-none">
                            Continue reading
                        </a>
                    {% else %}
                        <p class="card-text mb-auto content">{{ post.content |urlize }}</p>
                    {% endif %} 
                </div>
            </div>
            </div>
        </div>
        
    {% endfor %}
</div>

{% if pag_posts.total > 5 %}

{{render_pagination(pag_posts, "views.index", name = "pagination for index page" )}}

{% endif %}
{% endblock %}

stud_corner/templates/login.html
{% from "app_macros.html" import input, button with context %}
{% extends "layout.html" %}

{% set active_page = "login" %}

{% block title %}Login Page{% endblock %}

{% block content %}

<div class="container col-11 col-md-4 rounded shadow-sm mt-4 mb-5 bg-white">
    <div class="row justify-content-center">
        <form class="col-12 p-3" method="POST">
            <h1 class="h3 fw-normal">Log in</h1>
            <hr>
            <div class="form-floating my-3">
                {{ input("email", type="email", label = "Email Address") }}
            </div>
            <div class="form-floating mb-3">
                {{ input("password", type="password", label = "Password") }}
            </div>

            {% with messages = get_flashed_messages(with_categories = true) %}
            {% if messages %}
                {% for category, message in messages %}
                {% if category == "password-alert" %}
                <div>
                    {{ message }}<a href="{{ url_for('auth.reset_password_request') }}" class="text-decoration-none">Click here</a>
                </div>
                {% endif %}
                {% endfor %}
            {% endif %}
            {% endwith %}
              

            <div class="checkbox my-3">
                <label>
                    <input type="checkbox" name="remember" value="remember-me"> Remember me
                </label>
            </div>
            <div class="d-flex justify-content-center">   
                {{ button(label = "Sign in") }}
            </div>
        </form> 
    </div>
</div>
{% endblock %}

stud_corner/templates/navbar.html
<nav class="navbar navbar-expand-lg sticky-top navbar-dark background">
    <div class="container-fluid">
        <a class="navbar-brand fw-bold h1" href="/">Student Corner</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-lg-0">
                <li class="nav-item mx-lg-2">
                    <a class="nav-link fw-bold {% if active_page=='index' %}active{% endif %}" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item me-lg-2">
                    <a class="nav-link fw-bold {% if active_page=='about' %}active{%endif %}" aria-current="page" href="#">About</a>
                </li>
                <li class="nav-item me-lg-2">
                    <a class="nav-link fw-bold {% if active_page=='contacts' %}contacts{%endif %}" aria-current="page" href="#" tabindex="-1">Contacts</a>
                </li>
            </ul>
            {% if active_page== "index" or active_page== "author" or active_page== "post" %}
            <form class="col-12 col-lg-6 d-none d-lg-block">
                <input type="search" name="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search" autocomplete="off" autofocus>
            </form>
            {% endif %}
            <ul class="navbar-nav ms-auto mb-lg-0">
                {% if current_user.is_authenticated %}
                    <li class="nav-item mx-lg-2">
                        <a class="nav-link fw-bold {% if active_page=='post' %}active{%endif %}" aria-current="page" href="{{ url_for('views.post') }}">Your posts</a>
                    </li>
                    <li class="nav-item me-lg-2">
                        <a class="nav-link fw-bold {% if active_page=='profile' %}active{%endif %}" aria-current="page" href="{{ url_for('views.profile') }}">Your profile</a>
                    </li>
                    <li class="nav-item me-lg-2">
                        <a class="nav-link fw-bold" href="{{ url_for('auth.signout') }}">Sign out</a>
                    </li>
                {% else %}

                    <li class="nav-item me-lg-2">
                        <a class="nav-link fw-bold {% if active_page=='signin' %}active{%endif %}" aria-current="page" href="{{ url_for('auth.signin') }}">Sign in</a>
                    </li>
                    <li class="nav-item me-lg-2">
                        <a class="nav-link fw-bold {% if active_page=='signup' %}active{%endif %}" aria-current="page" href="{{ url_for('auth.signup') }}">Sign up</a>
                    </li>
                {% endif %}

            </ul>
            {% if active_page == "index" or active_page=="author" or active_page== "post" %}
            <form class="col-12 d-lg-none">
                <input type="search" name="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search" autocomplete="off" autofocus>
            </form>
            {% endif %}      
            
        </div>
    </div>             
</nav>

stud_corner/templates/profile.html
{% from "app_macros.html" import render_pagination, input, button, textarea with context %}

{% extends "layout.html" %}
{% set active_page = "profile" %}

{% block title%}Your Profile{% endblock %}

{% block content %}
    <div class="container col-11 col-md-6 mt-3 mb-3">
        <div class="fs-3 me-5">
           <h3 class="fw-bold">{{ "%s %s" %(firstname, lastname) }}</h3>
        </div>
        <p>{{email}}</p>
        
        <h4 class="fw-normal border-bottom border-secondary">Update Profile</h4>
        <form method="POST">
            <div class="form-floating mb-3">
                {{ input("email", type="email", value= email, label = "Email Address") }}

            </div>
            <div class="form-floating mb-3">
                {% if bio %}
                    {{ textarea("bio", id="floatingTextarea2", value = bio , label = "Add Bio") }}
                {% else %}
                    {{ textarea("bio", id="floatingTextarea2", label = "Add Bio") }}
                {% endif %}

            </div>
            <div class="d-flex justify-content-center mb-3">   
                {{ button(label = "Update Profile") }}
            </div>
        </form>
    </div>
{% endblock %}

stud_corner/templates/read_more.html
{% from "app_macros.html" import render_pagination, input, button, textarea with context %}

{% extends "layout.html" %}

{% block meta %}
      <meta name="author" content= "{{ '%s %s' %(post.author.firstname, post.author.lastname) }}">
      <meta name="description" content="{{ post.title }}">
      <meta name="keywords" content="{{ post.subject }}">
{% endblock %}
{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <div class="container col-md-7 my-3">
        <div class="row justify-content-center">
            <div class="row card-bg g-0 border rounded overflow-hidden mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success">{{ post.subject |title }}</strong>
                    <h3 class="mb-0">{{ post.title |title }}</h3>
                    <div class="mb-1 text-muted">{{ post.date_posted.strftime("%d %B %Y") }}
                        by 
                        <a href="{{ url_for('views.author', id = post.author.id) }}" class="text-decoration-none link-dark">
                            {{ ("%s %s" %(post.author.firstname, post.author.lastname)) |title}}
                        </a>
                    </div>
                    <p class="card-text mb-auto content">{{ post.content |urlize }}</p> 
                </div>
            </div>
        </div>
        <form method="POST">
          <div class="form-floating mb-3">
            {{ textarea("content", id="CommentsTextarea", label = "Comment") }}
          </div>
          <div class="d-flex justify-content-center mb-3">   
            {{ button(class="w-30 btn btn-sm btn-primary") }}
          </div>
        </form>        
          <div class="d-flex w-100 justify-content-between border-bottom border-secondary mb-1">
            <strong>Comments</strong>
            <p>{{comments.total}} {% if comments.total > 1 %}comments{% else %}comment{% endif %}</p>
          </div>
          <ul class="list-group">
              {% for comment in comments.items %}
              <div class="mb-2 border">
                <div class="d-flex w-100 justify-content-between px-1 border-bottom">
                  <strong>
                    <a href="{{ url_for('views.author', id = comment.commentor.id) }}" class="text-decoration-none link-dark">
                      {{ comment.commentor.firstname }} {{ comment.commentor.lastname }}
                    </a>
                  </strong>
                  <small time-delta="{{ comment.date_commented }}" ></small>
                </div>
                <p class="mb-1 content">{{ comment.content }}</p>
              </div>
                {% endfor %}
          </ul>
    </div>
  {% if comments.total > 10 %}
    {{render_pagination(comments, "views.read_more", id=post.id, name = "pagination for comments" )}}
  {% endif %}
{% endblock %}
    

stud_corner/templates/renew_password.html
<p>Please follow this link to renew your password:</p>
<p><a href="{{ reset_password_url }}">{{ reset_password_url}}</a></p>

<p>Have a nice time using our app!</p>

stud_corner/templates/reset_password_form.html
{% from "app_macros.html" import input, button with context %}

{% extends "layout.html" %}

{% block title %}Reset Password Form{% endblock %}

{% block content %}
<div class="container col-11 col-md-4">
    <form method="POST">
        <h1 class="h3 fw-normal mt-4 border-bottom border-secondary">Enter New Password</h1>
        <div class="form-floating my-3">
            {{ input("password1", type="password", label = "Password") }}           

        </div>
        <div class="form-floating mb-3">
            {{ input("password2", type="password", label = "Confirm Password") }}
        </div>
        <div class="d-flex justify-content-center">   
            {{ button() }}
        </div>
    </form> 
</div>

{% endblock %}

stud_corner/templates/reset_password_request.html
{% extends "layout.html" %}

{% block title %}Reset Password Request{% endblock %}

{% block content %}

<div class="container col-md-5 bg-white my-5 border">
    <div class="row justify-content-center">
        <form class="col-md-10" method="POST">
            <h1 class="h3 mb-3 fw-normal mt-5">Enter Your Registered Email Address</h1>
    
            <div class="form-floating my-3">
                <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com" autocomplete="off" autofocus required>
                <label for="floatingInput">Email address</label>
            </div>
            <div class="d-flex justify-content-center">   
                <button class="w-30 btn btn-lg btn-primary mb-5" type="submit">Submit</button>
            </div>
        </form> 
    </div>
</div>
{% endblock %}

stud_corner/templates/signin.html
{% from "app_macros.html" import input, button with context %}
{% extends "layout.html" %}

{% set active_page = "signin" %}

{% block title %}Sign In{% endblock %}

{% block content %}

<div class="container col-11 col-md-4 mt-4 mb-5">
    <form method="POST">
        <h1 class="h3 fw-normal border-bottom border-secondary">Sign in</h1>
        <div class="form-floating my-3">
            {{ input("email", type="email", label = "Email Address") }}
        </div>
        <div class="form-floating mb-3">
            {{ input("password", type="password", label = "Password") }}
        </div>

        {% with messages = get_flashed_messages(with_categories = true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == "password-alert" %}
            <div>
                {{ message }}<a href="{{ url_for('auth.reset_password_request') }}" class="text-decoration-none">Click here</a>
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}
            

        <div class="checkbox my-3">
            <label>
                <input type="checkbox" name="remember" value="remember-me"> Remember me
            </label>
        </div>
        <div class="d-flex justify-content-center">   
            {{ button(label = "Sign in") }}
        </div>
    </form> 
</div>
{% endblock %}

stud_corner/templates/update_post.html
{% from "app_macros.html" import input, textarea, button with context %}

{% extends "layout.html" %}

{% block content %}

<div class="container col-md-6 mt-3">
    <form method="POST">
        <h1 class="h3 fw-normal border-bottom border-secondary">Update Post</h1>
        <div class="form-floating mb-3">
            {{ input("subject", value = to_update_post.subject, label = "Subject") }}

        </div>
        <div class="form-floating mb-3">
            {{ input("title", value= to_update_post.title, label = "Title") }}

        </div>
        <div class="form-floating mb-3">
            {{ textarea("content", id="floatingTextarea2", value= to_update_post.content, label = "Update Post") }}

        </div>
        <div class="d-flex justify-content-center mb-3">   
            {{ button() }}
        </div>
    </form>
</div>

{% endblock %}